// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleRestAPI.Data;

#nullable disable

namespace SimpleRestAPI.Migrations
{
    [DbContext(typeof(SchoolsDbContext))]
    [Migration("20250222133013_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleRestAPI.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            City = "City 1",
                            Name = "School 1",
                            SecretValue = "Secret 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            City = "City 2",
                            Name = "School 2",
                            SecretValue = "Secret 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address 3",
                            City = "City 3",
                            Name = "School 3",
                            SecretValue = "Secret 3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address 4",
                            City = "City 4",
                            Name = "School 4",
                            SecretValue = "Secret 4"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address 5",
                            City = "City 5",
                            Name = "School 5",
                            SecretValue = "Secret 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
